version: "3"
services:
  backend:
    build: "."
    image: "node-server"
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    links:
      - "db:database"
  db:
    restart: "on-failure"
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "public"
    expose:
      - 5432
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
